INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());


INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Books', Now());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics',Now());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', Now());
